# Generated by Django 4.1.5 on 2024-02-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lname', models.CharField(max_length=50)),
            ],
        ),
    ]
