# Generated by Django 4.1.5 on 2024-02-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0003_rename_lname_sports_sportsname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=100, null=True)),
                ('time', models.TimeField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.location')),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.sports')),
            ],
        ),
    ]
