# Generated by Django 4.1.5 on 2024-02-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0004_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.ForeignKey(default='gr', on_delete=django.db.models.deletion.CASCADE, to='sports_app.location'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sports',
            field=models.ForeignKey(default='gr', on_delete=django.db.models.deletion.CASCADE, to='sports_app.sports'),
        ),
    ]
