# Generated by Django 4.1.5 on 2024-03-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0006_organizer_reg_manager_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='count',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
