# Generated by Django 5.0.3 on 2024-03-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0008_remove_user_reg_count_manager_reg_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_reg',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
