# Generated by Django 4.1.5 on 2024-03-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports_app', '0006_organizer_reg_manager_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('Eventname', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=100, null=True)),
                ('time', models.TimeField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('fee', models.CharField(max_length=1000, null=True)),
                ('payment', models.CharField(max_length=1000, null=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_app.organizer_reg')),
                ('sports', models.ForeignKey(default='gr', null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_app.sports')),
            ],
        ),
        migrations.CreateModel(
            name='send_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.manager_reg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='join_tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=1000, null=True)),
                ('Tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.createtournament')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_app.manager_reg')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_app.organizer_reg')),
            ],
        ),
    ]
